- name: will wait till reachable
  hosts: all
  gather_facts: false # we just created the EC2 machine, so we want for the machine to become accessible before gathering facts
  ignore_unreachable: true
  tasks:
    # - name: Wait for system to become reachable
    #   ansible.builtin.wait_for_connection:
    #     timeout: 180

    - name: Gather facts for the first time
      ansible.builtin.setup:

    - name: configure the login banner
      connection: network_cli
      arista.eos.eos_banner:
        banner: login
        text: |
          this is my login banner2
          that contains a multiline
          string
        state: present